"""
Django settings for shwipt_app project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from firebase_admin import credentials, initialize_app

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pa=8jmv#h)_0a+*p4x9n5mjwh-u1v-bw61v%j%*(5^f1%y-ojx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'development.shwipt.tech',
    'staging.shwipt.tech',
    'production.shwipt.tech',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shwipt_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shwipt_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

creds = credentials.Certificate({
    "type": os.environ.get("type"),
    "project_id": os.environ.get("project_id"),
    "private_key_id": os.environ.get("private_key_id"),
    "private_key": os.environ.get("private_key").replace('\n', '\n'),
    "client_email": os.environ.get("client_email"),
    "client_id": os.environ.get("client_id"),
    "auth_uri": os.environ.get("auth_uri"),
    "token_uri": os.environ.get("token_uri"),
    "auth_provider_x509_cert_url": os.environ.get("auth_provider_x509_cert_url"),
    "client_x509_cert_url": os.environ.get("client_x509_cert_url")
})
default_app = initialize_app(creds)

# creds = credentials.Certificate({
#   "type": "service_account",
#   "project_id": "shwipt-dev",
#   "private_key_id": "e1804c0a7887e503fb4a374d8c01f67c3131cfc0",
#   "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCp1W3QBaPzMEuq\nXWivQrf2ma4daZ/jurdAU56kEKDx7BvCz5ro0txR7DGHo1NEPO5FnvOvvcMtZ1AM\nz4/r2hP8XcrKdFiwsVI8DBA3G0SmV22zT/xq+KlpYqvUzWbN/kYV6imPK/9fHeuz\nOb5Mp+mf7XAvOlkGKpWj0nVEtnPC5QeSr1axJshlNAAoh0da/4qCexZCfgnhlSvG\nz55M7+2C4gs8NvoAK0q+W9f/2EY9o7C8qQHQ6UQXiT8+o/lyilDCovCbsj+FBsKe\nZzYX8E3kLfg/08RxmkJEQMiqeNJ1wYqaOHTHrsPu8W2QLIGsubYIwUrVp868+eC8\nXktLm9cDAgMBAAECggEACzjdpTnCMB8YWN0MPkx30HUuMqZYmNktI7SCzo+Euweh\ne/lw4IKSaV1klnRd26v1CKesrYep/nWNrhMHDQwfdvURodgXRjGpX+tiJOoJ2r37\nMzaNVNoyg5KwDQM3kFQFeIw9C8dZ/ASDnxepMfKEdvtfBtfhqw0kTytocU5nDtEs\n3zFvLwlL59qkGuIE4oHAHxZOH5J3i8Lj6GS2Hg4I20vb8ejioNlai6hUsPlSbmnB\nlbYXZ7ayafYBBfXq+79ailh5glgVpC+/D8AKVA4f/7eoQR+Z3UMEb3JHKGWVcp+I\n1/jPS9dwOrWJru4lDnWZ/+khgzaXfolZCcHEvwa80QKBgQDZK2TtG8cTcm4/AqLP\ntfwOM+3tAgD22RIfgGUb296XtRa2kXBQAUfZ2fn6Fy/zP7hjxhP8TJWB5xFbmoH3\njK5+hVilUd47YSfAulUGsVDWrx7ncV1I67cRGW0Ugi7LtiNumcajhk21W1jAqqpo\noJEMGVsoXa3fUYdfBwzi0XmjEQKBgQDIM09bGhbo0Dd3OPq89MCl2Fqp+7tYewXF\npQ2UR2HbFwaUb9kL90N7AA5BvKy74OlwSWSCpYO5KjT4qKid7HWunEm9t6E8m+l0\nyEBKaToMuElEQAC5mjrv/piNbST/6I5i+Dftaj5hp57rHheK9QF4/JqD/S/lPode\nvDdlptNw0wKBgA9GsCjFpXFGwV6JTu6RfJN7L6dWVr8GcfHpVDNrefLt+BULkfzu\nuiEm5iCjdOoFd3D9Q/ahZHroyB3Ldoz1Rmj79EpcwecnZGZ4NPbtjiQr2V6qaMdy\nXUREp5mjtqr5uvBSvNhP4DN7o3iaCLanZMyXFAR44nws/fq/QjbKSWYhAoGAac7c\neQyv4Pny5psBwg4lJ0HSoRY/bMMQSOYz6BNV/6IKwzbd4robOw3LeyjJrj5vgf34\nFih+FsXc2zLgcx6/D7rgKlm76LmKSENx3yIAISrg5iZhe7aswZywacaukGYLovkH\nLf5B3ADoN+Felf1petUeoPWWc7V5fDNDoADsrSsCgYEAxdXY+bt1RJ4x6sZyZeri\n7iNZxJbLfzP2dWNGh5baBgBdbnYyREse051SzkM2QhgIGtxmWagBm3azCOIH7wJt\nE+rbTftdZVsrJwQG3DpvDw8m/MXYet5fqNAOurnp4oMGGgDvyHdrPO2Ys4Id2BfC\nrX1KptaxyjECUeQ8aC4j4BM=\n-----END PRIVATE KEY-----\n",
#   "client_email": "firebase-adminsdk-8u2gz@shwipt-dev.iam.gserviceaccount.com",
#   "client_id": "111104411798375737583",
#   "auth_uri": "https://accounts.google.com/o/oauth2/auth",
#   "token_uri": "https://oauth2.googleapis.com/token",
#   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
#   "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-8u2gz%40shwipt-dev.iam.gserviceaccount.com"
# })

# default_app = initialize_app(creds)